dependencies:
  - aave/aave-v3-core@1.16.2
compiler:
  solc:
    remappings:
      - "@aave=aave/aave-v3-core@1.16.2"

dotenv: .env
networks:
  default: goerli
  goerli:
    weth_token: "0x2e3A2fb8473316A02b8A297B982498E661E1f6f5"
    lending_pool_addresses_provider: "0xc4dCB5126a3AfEd129BC3668Ea19285A9f56D15D"
    link_eth_price_feed: "0xb4c4a493AB6356497713A78FFA6c60FB53517c63"
    link_token: "0x07C725d58437504CA5f814AE406e70E21C5e8e9e"
wallets:
  from_key: ${PRIVATE_KEY}
